# Generated by Django 3.1 on 2020-11-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('cod_est', models.AutoField(primary_key=True, serialize=False)),
                ('des_est', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('cod_rol', models.AutoField(primary_key=True, serialize=False)),
                ('des_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('cod_per', models.AutoField(primary_key=True, serialize=False)),
                ('ced_per', models.CharField(max_length=100)),
                ('nom_per', models.CharField(max_length=100)),
                ('fna_per', models.DateField()),
                ('dir_per', models.CharField(max_length=100)),
                ('ema_per', models.CharField(max_length=100)),
                ('pas_per', models.CharField(max_length=100)),
                ('fk_perest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasM.estados')),
                ('fk_perrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasM.roles')),
            ],
        ),
    ]
