# Generated by Django 3.1 on 2020-11-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitasM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('cod_est', models.AutoField(primary_key=True, serialize=False)),
                ('des_est', models.CharField(max_length=50)),
            ],
        ),
    ]
