# Generated by Django 3.1.3 on 2020-11-29 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CitasM', '0002_doctores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('cod_cit', models.AutoField(primary_key=True, serialize=False)),
                ('fec_cit', models.DateField()),
                ('hor_cit', models.CharField(max_length=100)),
                ('fk_citdoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasM.doctores')),
                ('fk_citest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasM.estados')),
                ('fk_citper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasM.personas')),
            ],
        ),
    ]
