# Generated by Django 3.1.3 on 2020-11-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitasM', '0003_citas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fk_citper',
            field=models.CharField(max_length=100),
        ),
    ]
