# Generated by Django 3.1.3 on 2020-11-30 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CitasM', '0004_auto_20201129_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fk_citper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CitasM.personas'),
        ),
    ]
