# Generated by Django 3.1.3 on 2020-11-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CitasM', '0005_auto_20201129_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='obs_cit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
